### ISSUE TITLE
[Question] Verical pulley alignment

### ISSUE THREAD

**Issue by hakimio** [chilimangoes/eva_coreception_mod#3]
Hi @chilimangoes 

I am wondering what vertical distances did you use when positioning belt holders/clamps on EVA carriage. The original pulleys from the factory seem to be extremely misaligned: the lower pulleys on X gantry way higher than the pulleys in the front of the printer. The lower pulley in front is around 29mm from the Y gantry and the one on X gantry is around 27mm from the Y gantry. I am currently designing pulley holder bracket for holding larger pulleys in front of the printer (instead of the metal original part) and I am trying to decide what vertical pulley distances I should use. Have you installed bigger pulleys and proper shoulder bolts? What measurements did you use?

![original pulleys](https://user-images.githubusercontent.com/768105/121405793-bde56100-c95d-11eb-98ed-47694978d460.png)
![idler bracket](https://user-images.githubusercontent.com/768105/121405805-c2117e80-c95d-11eb-8750-efe9c18caa18.png)

**Comment by chilimangoes** [comment]
Hi @hakimio 

Sorry, I just saw this today. Yeah, the lower pulleys are pretty misaligned from factory. I tried to line my belt anchor locations as closely as I could with the idler pulleys on the front of the printer. That way, when I finally get around to replacing the idlers on the gantry, I can line those up with the front idlers and everything should be even.

For reference, here are the measurements I used for the anchor locations. Vertical measurements are from the bottom of the gantry to the centerline of the anchor point.

Upper belt: 5.4 mm to centerline
Lower belt: 15.1 mm to centerline

Visual example:
![image](https://user-images.githubusercontent.com/1724779/121766641-5881a380-cb08-11eb-9763-83b82dbed5d6.png)

And from my measurements, you would add ~19 mm to get the vertical distance from the under side of the halo to the centerlines of the pulleys. Hopefully that all makes sense.

I still plan to replace the pulleys and use shoulder bolts, but it hasn't been a priority because it's printing fine and I've been crazy busy with other projects. I don't have any plans to use bigger pulleys though. I just plan on using the same size idlers as stock because I got a bunch of them for my Voron build. On the gantry, I plan to use F695 bearings in place of the front idlers - again, because that's what the Voron uses for smooth idlers.

**Comment by hakimio** [comment]
Makes perfect sense. Thank you for detailed explanation.

Just one more small question: have you installed or do you plan to install `adxl345` accelerometer? How is it supposed to be mounted on your EVA mod?

**Comment by chilimangoes** [comment]
Yes! Which actually reminded me that I had designed a newer version of the fan shroud, with additional mounting holes on the bottom for an ADXL345. I've uploaded the new shroud and updated the README with information on 3 different accelerometer mounting options.

Here:
https://github.com/chilimangoes/eva_coreception_mod/blob/main/README.md#adxl345--accelerometer-mounting-options

**Comment by hakimio** [comment]
Thanks. Which mount are you using yourself?

**Comment by chilimangoes** [comment]
I'm currently using option 1. I plan to switch to option 3, but I haven't printed the new shroud yet.
